[package]
name = "watchlist"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.5.50", features = ["derive"] }
ron = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
